# Generated by Django 5.0.7 on 2024-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=15)),
                ('km', models.IntegerField(default=-1)),
                ('last_inspection_date', models.DateField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
