# Generated by Django 5.1 on 2024-08-12 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_car_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='km',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='last_inspection_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
