# Generated by Django 5.1 on 2024-08-13 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_alter_car_km_alter_car_last_inspection_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='max_passenger',
        ),
        migrations.AddField(
            model_name='booking',
            name='ride',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='gestione.ride'),
        ),
        migrations.AddField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='my_bookings', to='gestione.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='close_registration_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='open_registration_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='my_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_location',
            field=models.CharField(max_length=30),
        ),
    ]
