# Generated by Django 5.1 on 2024-08-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_remove_booking_car_remove_ride_max_passenger_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
