# Generated by Django 5.1 on 2024-08-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0009_alter_booking_close_registration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='review_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.review'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='gestione.ride'),
        ),
    ]
