# Generated by Django 5.1 on 2024-08-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0010_alter_passenger_review_id_alter_passenger_ride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers_ride', to=settings.AUTH_USER_MODEL),
        ),
    ]
