# Generated by Django 5.1 on 2024-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0013_remove_passenger_unique_ride_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
