# Generated by Django 5.1 on 2024-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0015_remove_booking_ride_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ride',
            name='ride_primary_key',
        ),
    ]
