# Generated by Django 5.1 on 2024-08-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0016_remove_ride_ride_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='my_rides', to='gestione.car'),
        ),
    ]
