# Generated by Django 5.1 on 2024-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0018_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ride_images/'),
        ),
    ]
