# Generated by Django 5.1 on 2024-09-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0019_ride_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrival_address',
            field=models.CharField(default='NO_ADDRESS_A', max_length=30),
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_state',
            field=models.CharField(default='NO_STATE_A', max_length=30),
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_address',
            field=models.CharField(default='NO_ADDRESS_D', max_length=30),
        ),
        migrations.AddField(
            model_name='ride',
            name='departure_state',
            field=models.CharField(default='NO_STATE_D', max_length=30),
        ),
    ]
