# Generated by Django 5.1 on 2024-09-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0020_ride_arrival_address_ride_arrival_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arrival_location',
            field=models.CharField(default='NO_LOCATION_A', max_length=30),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default='NO_TIME_A'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='close_registration_time',
            field=models.DateTimeField(default='NO_CLOSE_TIME'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_location',
            field=models.CharField(default='NO_LOCATION_D', max_length=30),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(default='NO_TIME_D'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='open_registration_time',
            field=models.DateTimeField(default='NO_OPEN_TIME'),
        ),
    ]
