# Generated by Django 5.1 on 2024-09-04 09:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0021_alter_ride_arrival_location_alter_ride_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='review_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestione.review'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 23, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='close_registration_time',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 23, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 23, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ride',
            name='open_registration_time',
            field=models.DateTimeField(default=datetime.datetime(1969, 12, 31, 23, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
