# Generated by Django 5.1 on 2024-09-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0023_alter_car_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='review_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione.review'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_rides', to='gestione.car'),
        ),
    ]
