# Generated by Django 5.1 on 2024-09-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0024_alter_passenger_review_id_alter_ride_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='review_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewers', to='gestione.review'),
        ),
    ]
